---
name: Test
on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # latest 2 versions
        go: [ 1.15, 1.16 ]
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: go test
